### ISSUE TITLE
How to get sequence position at path node efficiently?

### ISSUE THREAD

**Issue by subwaystation** [ekg/xg#54]
Hi vgteam :)

Let's say I have a path _p_ and a node _n_ ε _p_. Now I want to know the sequence position of the node's first base in the given path. As far as I examined your code, I can not find any method capable of doing that. I only found the inverse method

  `int64_t node_at_path_position(const string& name, size_t pos) const;`

in `xg`. Maybe you can lend me a hand there? My current understanding of the code is not deep enough to implement this myself, but if you point me to the right direction I would gladly implement this.

Thanks!

**Comment by glennhickey** [comment]
https://github.com/vgteam/xg/blob/f58434744afd54491279cdb397dd87576fba2402/src/xg.hpp#L161

**Comment by subwaystation** [comment]
Well, not having the current version of `xg` it is not surprising I did not see this... :(
Thanks Glenn!
